### ISSUE TITLE
The game doesn't run properly on desktop! (at least on Linux)

### ISSUE THREAD

**Issue by hugomartin89** [danirod/rectball#24]

**Comment by danirod** [comment]
Can confirm it coredumps on Arch Linux. Already investigating it.

**Comment by danirod** [comment]
Can confirm works on Arch Linux after merging #26. The fact that it worked on MacOS X, probably because on MacOS windows don't have icons. I think I f***d up the icon during some graphics update because of not looking at the sizes. Already generating JAR.

I'm keeping this issue opened until I can test it works on Windows tomorrow.

**Comment by danirod** [comment]
Runs on Windows.
