### ISSUE TITLE
Fullscreen partially works on Android 7.1.1

### ISSUE THREAD

**Issue by Guerra24** [danirod/rectball#76]
The fullscreen mode still shows the nav bar.

![img](https://puu.sh/waUF8/70787a85c4.png)

**Comment by danirod** [comment]
I already know.

Let this be the tracking issue.

**Comment by danirod** [comment]
It's believed that this is fixed in the latest Build (413). Because this issue only happens a percentage of the times the game is launched in fullscreen mode, a follow up will be required to check if this issue is still seen in the wild.

**Comment by danirod** [comment]
After some UI testing in Builds 413 and 414, this seems to be finally fixed.

**Comment by danirod** [comment]
FYI, found the technical details on this bug.

This is known as [low profile mode](https://developer.android.com/training/system-ui/dim.html). Apparently this mode is designed to keep the system bars so that the content of the activity doesn't scale; however they get dimmed so that they don't distract.
